In [1]:
import preprocessing as prep
import pandas as pd
import numpy as np
from stats import generate_report

In [2]:
data = pd.read_csv(r'C:\Users\josee\OneDrive\Documentos\GitHub\synchrony_pipeline\src\C1\inputs\rawdata\S2R2\Raw.csv')
markers = pd.read_csv(r'C:\Users\josee\OneDrive\Documentos\GitHub\synchrony_pipeline\src\C1\inputs\rawdata\S2R2\markers.csv')

In [3]:
segments = prep.segment_by_markers(data, markers)
segments

{'baseline':               TP9         AF7         AF8        TP10
 0     -219.726562  -86.914062   28.808594 -182.128906
 1     -191.406250  -91.796875    5.859375 -164.550781
 2     -187.988281 -113.769531   -8.300781 -173.339844
 3     -178.222656 -100.097656   -8.300781 -150.878906
 4     -122.558594  -66.894531   -1.953125  -83.984375
 ...           ...         ...         ...         ...
 78268  -25.390625  110.351562  427.246094  -46.875000
 78269  -27.343750  106.445312  473.632812  -42.480469
 78270  -11.718750  108.886719  560.058594  -32.714844
 78271  -13.183594  114.746094  697.753906  -25.390625
 78272  -17.089844  109.863281  845.703125  -30.273438

 [78273 rows x 4 columns],
 'shared':               TP9         AF7         AF8        TP10
 78273  -13.183594  112.792969  862.792969  -32.226562
 78274  -22.949219  112.792969  821.289062  -31.738281
 78275  -18.066406  113.281250  756.835938  -11.230469
 78276  -30.273438  114.257812  669.921875  -24.902344
 78277  -38.574219  105.957031  651.367188  -33.203125
 ...           ...         ...         ...         ...
 162504 -80.078125  -42.480469 -207.031250 -134.277344
 162505 -81.054688  -50.781250  -90.820312 -128.906250
 162506 -79.101562  -42.480469  167.968750 -119.628906
 162507 -62.988281  -34.667969  108.398438 -128.417969
 162508 -62.011719  -34.667969 -251.464844 -137.695312

 [84236 rows x 4 columns],
 'individual':               TP9        AF7         AF8        TP10
 162509 -86.425781 -30.273438 -389.648438 -133.300781
 162510 -85.937500 -18.554688 -158.691406 -122.070312
 162511 -63.964844 -22.460938  -12.695312 -115.722656
 162512 -64.941406 -31.738281 -619.140625 -119.140625
 162513 -68.847656 -40.527344 -604.492188 -121.093750
 ...           ...        ...         ...         ...
 236778 -56.640625 -23.925781 -375.976562  -40.039062
 236779 -52.734375 -38.574219 -483.398438  -47.851562
 236780 -54.199219 -49.316406 -894.042969  -48.339844
 236781 -54.199219 -52.246094 -622.070312  -46.386719
 236782 -58.593750 -52.246094  -15.136719  -53.710938

 [74274 rows x 4 columns]}

In [28]:
import json

# params = {
#     "filter_order": 2,
#     "bandwidth": [4, 50],
#     "type": "bandpass",
#     "fs": 256,
#     "output": "sos"
# }

# with open("filter_params.json", "w") as f:
#     json.dump(params, f, indent=4)

window_config_path = r"C:\Users\josee\OneDrive\Documentos\GitHub\synchrony_pipeline\src\C1\inputs\proc_config.json"
with open(window_config_path, "r") as f:
    window_config = json.load(f)
window_config["bandfreqs"]

{'theta': [4, 8], 'alpha': [8, 13], 'beta': [13, 30], 'gamma': [30, 50]}

In [5]:
filtered = prep.digfilter(segments['baseline'])

In [6]:
filtered

             TP9        AF7         AF8       TP10
0      -4.676355   0.430280   -0.648828  -5.852448
1      -8.410057 -12.626551  -24.644181 -18.636175
2     -11.005140 -15.986670  -40.747471 -22.853301
3      -3.895023  -4.914531  -44.100347 -10.335192
4      14.545375  11.590830  -34.076898  12.312950
...          ...        ...         ...        ...
78268  -0.977809   3.098248 -198.516140  -9.509470
78269   1.067007   5.038650 -190.850727  -8.943660
78270   3.962381   5.965224 -157.553389  -3.643425
78271   4.902338   5.099900  -84.794891   0.682710
78272   2.327958   2.298998   14.113014   1.092959

[78273 rows x 4 columns]

In [7]:
segments['baseline']

              TP9         AF7         AF8        TP10
0     -219.726562  -86.914062   28.808594 -182.128906
1     -191.406250  -91.796875    5.859375 -164.550781
2     -187.988281 -113.769531   -8.300781 -173.339844
3     -178.222656 -100.097656   -8.300781 -150.878906
4     -122.558594  -66.894531   -1.953125  -83.984375
...           ...         ...         ...         ...
78268  -25.390625  110.351562  427.246094  -46.875000
78269  -27.343750  106.445312  473.632812  -42.480469
78270  -11.718750  108.886719  560.058594  -32.714844
78271  -13.183594  114.746094  697.753906  -25.390625
78272  -17.089844  109.863281  845.703125  -30.273438

[78273 rows x 4 columns]

In [8]:
import glob
import os

# cwd = os.getcwd()
# folderpath = os.path.join(cwd, "inputs", "rawdata")
# # Sessions of interest
# sessions = [2, 12, 14, 21, 27, 28, 31, 39, 41, 42]
# # Stages
# stages = ["baseline", "shared", "individual"]
# # Se guardan los datos de las sesiones en un diccionario
# preprodata = {
#     "p1": {
#         "baseline": pd.DataFrame(),
#         "shared": pd.DataFrame(),
#         "individual": pd.DataFrame(),
#     },
#     "p2": {
#         "baseline": pd.DataFrame(),
#         "shared": pd.DataFrame(),
#         "individual": pd.DataFrame(),
#     },
# }

# for sn in sessions:

#     p1raw = None
#     p2raw = None

#     pattern = f"S{sn}R*"
#     snpath = glob.glob(os.path.join(folderpath, pattern))[0]

#     p1raw = pd.read_csv(os.path.join(snpath, "Raw.csv"))

#     p2raw = pd.read_csv(os.path.join(snpath, "Raw2.csv"))

#     markers = pd.read_csv(os.path.join(snpath, "markers.csv"))

#     p1parts = prep.segment_by_markers(p1raw, markers)
#     p2parts = prep.segment_by_markers(p2raw, markers)

#     for stage in stages:
#         p1filt = prep.filter(p1parts[stage])
#         p2filt = prep.filter(p2parts[stage])

#         if stage == "baseline":
#             p1filt = p1filt.iloc[2561:25601, :]
#         else:
#             p1filt = p1filt.iloc[2561:64001, :]

#         # Common mean reference
#         p1filt = p1filt.subtract(p1filt.mean(axis=1), axis=0)
#         p1filt.insert(loc=0, column="Session", value=np.ones([p1filt.shape[0], 1]) * sn)

#         if stage == "baseline":
#             p2filt = p2filt.iloc[2561:25601, :]
#         else:
#             p2filt = p2filt.iloc[2561:64001, :]

#         p2filt = p2filt.subtract(p2filt.mean(axis=1), axis=0)
#         p2filt.insert(loc=0, column="Session", value=np.ones([p2filt.shape[0], 1]) * sn)

#         preprodata["p1"][stage] = pd.concat(
#             [preprodata["p1"][stage], p1filt], ignore_index=True
#         )

#         preprodata["p2"][stage] = pd.concat(
#             [preprodata["p2"][stage], p2filt], ignore_index=True
#         )

    # p1prep_df = pd.concat(p1prep, ignore_index=True)
    # p2prep_df = pd.concat(p2prep, ignore_index=True)

In [9]:
# preprodata['p1']['individual']

In [ ]:
cwd = os.getcwd()
folderpath = os.path.join(cwd, "inputs", "rawdata")
# Sessions of interest
sessions = [2, 12, 14, 21, 27, 28, 31, 39, 41, 42]
# Stages
stages = ["baseline", "shared", "individual"]

preprodata = prep.prepro(stages, sessions, folderpath)

In [11]:
preprodata['p1']['baseline']

        Session       TP9        AF7        AF8      TP10
0             2  3.938402   1.812123 -14.004608  8.254083
1             2  4.438536  -1.666868 -12.148694  9.377026
2             2 -0.716805  -3.504539  -2.465062  6.686406
3             2 -7.384797  -3.374002   9.727770  1.031029
4             2 -8.279308  -2.142740  15.868269 -5.446221
...         ...       ...        ...        ...       ...
230395       42  3.462936  -3.670610  -1.063166  1.270840
230396       42  4.418232  -7.750557   1.170794  2.161531
230397       42  4.836612 -10.496486   1.497188  4.162685
230398       42  3.011234 -10.780802   1.897426  5.872142
230399       42  0.129542  -9.359926   3.241114  5.989269

[230400 rows x 5 columns]

In [12]:
import processing as proc
from itertools import product
import mne
import mne_connectivity as mnec

# fs = 256
# winsz = 4
# ovlap = 0.5

# sessions = [2, 12, 14, 21, 27, 28, 31, 39, 41, 42]
# # sessions = [2]

# stages = ["baseline", "shared", "individual"]
# # stages = ["baseline"]

# # Freq bands of interest
# min_freq = 4
# max_freq = 50

# # Provide the freq points
# freqs = np.linspace(min_freq, max_freq, int((max_freq - min_freq) * 4 + 1))

# # The dictionary with frequencies are converted to tuples for the function
# fmin = tuple(np.arange(min_freq, max_freq, 1))
# fmax = tuple(np.arange(min_freq, max_freq, 1) + 1)

# # We will try two different connectivity measurements as an example
# connectivity_methods = ["pli", "wpli"]
# n_con_methods = len(connectivity_methods)

# channels = ['TP9', 'TP10', 'AF7', 'AF8']

# ch_names = ['TP9_1', 'TP10_1', 'AF7_1', 'AF8_1', 'TP9_2', 'TP10_2', 'AF7_2', 'AF8_2']

# indices = ([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3], [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7,])

# ch_comb = list(product(channels, repeat=2))

# conndata = {}

# for stage in stages:
#     sessdata = {}
#     for sn in sessions:
#         p1_data = preprodata['p1'][stage][ preprodata['p1'][stage]['Session'] == sn ].drop("Session", axis=1).to_numpy().T
#         p2_data = preprodata['p2'][stage][ preprodata['p2'][stage]['Session'] == sn ].drop("Session", axis=1).to_numpy().T
#         p1_holder = []
#         p2_holder = []

#         for i, (sig1, sig2) in enumerate(zip(p1_data, p2_data)):
#             p1_holder.append(proc.timewindow(sig1, fs, winsz, ovlap))
#             p2_holder.append(proc.timewindow(sig2, fs, winsz, ovlap))

#         p1_p2_arr = np.vstack((np.array(p1_holder),np.array(p2_holder)))
#         p1_p2_formatted = np.transpose(p1_p2_arr, (1, 0, 2))


#         info = mne.create_info(ch_names, fs, ch_types='eeg')
#         data_epoch = mne.EpochsArray(p1_p2_formatted, info)


#         # Pre-allocatate memory for the connectivity matrices
#         con_time_array = np.zeros(
#             (n_con_methods, p1_p2_formatted.shape[0], len(channels)**2, len(fmin))
#         )
#         con_time_array[con_time_array == 0] = np.nan  # nan matrix

#         # Compute connectivity over time
#         con_time = mnec.spectral_connectivity_time(
#             data_epoch,
#             freqs,
#             method=connectivity_methods,
#             sfreq=fs,
#             mode="cwt_morlet",
#             indices=indices,
#             fmin=fmin,
#             fmax=fmax,
#             faverage=True,
#             )
            
#         for c in range(n_con_methods):
#             con_time_array[c] = con_time[c].get_data(output="compact")

#         sessdata.update({f'S{sn}':con_time_array})


#     conndata[stage] = sessdata

In [13]:
# # Define estos nombres (si ya los tienes, usa los tuyos)        # len = 4
# ch_pairs     = [f"{i}_{j}" for i,j in ch_comb] # len = 16
# band_names   = [f"{i}-{j} Hz" for i,j in list(zip(fmin,fmax))]   # len = 26
# cols = [f"{i}_{j}" for i,j in list(product(ch_pairs, band_names))]

# dfs_by_stage = {}

# for stage in stages:
#     blocks = []

#     for sn in sessions:
#         for metric in range(0,2):
#             hd = conndata[stage][f'S{sn}'][metric, :, 0, :]
#             for ch in range(1,16):
#                 hd = np.hstack((hd, conndata[stage][f'S{sn}'][metric, :, ch, :]))
#             df_sess = pd.DataFrame(hd,columns=cols)
#             df_sess.insert(0, "Session", sn)
#             df_sess.insert(1, "Metric", connectivity_methods[metric])
#             df_sess.insert(2, "Epoch", np.arange(1,hd.shape[0]+1))

#             blocks.append(df_sess)

#     dfs_by_stage[stage] = pd.concat(blocks, axis=0, ignore_index=True)

In [14]:
# jaja = dfs_by_stage['baseline']
# jaja

In [15]:
fs = 256
winsz = 4
ovlap = 0.5

sessions = [2, 12, 14, 21, 27, 28, 31, 39, 41, 42]
# sessions = [2]

stages = ["baseline", "shared", "individual"]
# stages = ["baseline"]

# Freq bands of interest
min_freq = 4
max_freq = 50
channels = ['TP9', 'TP10', 'AF7', 'AF8']

# dfs_by_stage = proc.process(preprodata=preprodata, stages=stages, sessions=sessions, min_freq=min_freq, max_freq=max_freq, fs=fs, winsz=winsz, ovlap=ovlap, channels=channels)

In [16]:
# dfs_by_stage['baseline']

In [17]:
import pickle

# with open(r"outputs\dfs_by_stage.pkl", "wb") as f:
#     pickle.dump(dfs_by_stage, f)

with open(r"outputs\dfs_by_stage.pkl", "rb") as f:
    dfs_by_stage = pickle.load(f)

In [18]:
band_freqs = {'theta':[4,8], 'alpha':[8,13], 'beta':[13,30], 'gamma':[30,50]}
states = ['baseline', 'shared', 'individual']

band_procdata = proc.get_band_average(dfs_by_stage, band_freqs, stages, channels)

In [19]:
band_procdata['baseline']

,Session,Metric,Epoch,TP9_TP9_theta,TP9_TP9_alpha,TP9_TP9_beta,TP9_TP9_gamma,TP9_TP10_theta,TP9_TP10_alpha,TP9_TP10_beta,...,AF8_TP10_beta,AF8_TP10_gamma,AF8_AF7_theta,AF8_AF7_alpha,AF8_AF7_beta,AF8_AF7_gamma,AF8_AF8_theta,AF8_AF8_alpha,AF8_AF8_beta,AF8_AF8_gamma
0,2,pli,1,0.161670,0.191386,0.149204,0.040621,0.235128,0.175921,0.159229,...,0.091904,0.044033,0.258053,0.271255,0.169767,0.229617,0.153577,0.090211,0.095921,0.113461
1,2,pli,2,0.198240,0.210677,0.122321,0.084757,0.237111,0.157887,0.117663,...,0.112411,0.071050,0.185010,0.134712,0.151839,0.206151,0.170174,0.149487,0.117819,0.122140
2,2,pli,3,0.352384,0.165239,0.158872,0.268153,0.244033,0.170379,0.153377,...,0.115531,0.046674,0.132851,0.199666,0.243201,0.126063,0.222121,0.107670,0.145096,0.047596
3,2,pli,4,0.265625,0.101956,0.099839,0.090290,0.302677,0.128668,0.100573,...,0.103648,0.095092,0.142421,0.129238,0.144416,0.141948,0.245125,0.137892,0.116667,0.110165
4,2,pli,5,0.211829,0.161523,0.112343,0.041022,0.268363,0.167325,0.095904,...,0.123958,0.161937,0.093156,0.095871,0.115244,0.328305,0.117621,0.119907,0.125540,0.235672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,42,wpli,40,0.520392,0.305859,0.171311,0.066196,0.571897,0.312122,0.177990,...,0.180734,0.104676,0.440490,0.254651,0.191853,0.103647,0.265489,0.236575,0.179440,0.103225
876,42,wpli,41,0.552399,0.367589,0.258596,0.070254,0.460997,0.338362,0.256954,...,0.212597,0.087123,0.266525,0.253797,0.209023,0.083583,0.512046,0.231875,0.212418,0.085857
877,42,wpli,42,0.694662,0.387187,0.314224,0.048336,0.504898,0.345951,0.306716,...,0.228686,0.256610,0.572182,0.292044,0.228780,0.261996,0.547021,0.234977,0.233746,0.261891
878,42,wpli,43,0.759167,0.377907,0.267825,0.081305,0.414994,0.315973,0.256500,...,0.221320,0.249911,0.470400,0.180151,0.216969,0.246184,0.573383,0.194769,0.228817,0.257693
879,42,wpli,44,0.328346,0.162656,0.141073,0.175027,0.260723,0.130302,0.144869,...,0.148201,0.123715,0.490215,0.152346,0.151451,0.134076,0.217319,0.143007,0.153509,0.116100

In [20]:
procdata_norm = proc.normalize_by_baseline(band_procdata, stages)

In [21]:
band_procdata['shared']

,Session,Metric,Epoch,TP9_TP9_theta,TP9_TP9_alpha,TP9_TP9_beta,TP9_TP9_gamma,TP9_TP10_theta,TP9_TP10_alpha,TP9_TP10_beta,...,AF8_TP10_beta,AF8_TP10_gamma,AF8_AF7_theta,AF8_AF7_alpha,AF8_AF7_beta,AF8_AF7_gamma,AF8_AF8_theta,AF8_AF8_alpha,AF8_AF8_beta,AF8_AF8_gamma
0,2,pli,1,0.126158,0.119621,0.373038,0.519472,0.175022,0.072610,0.248743,...,0.227856,0.386322,0.322972,0.200309,0.387674,0.560234,0.116520,0.099105,0.346872,0.493137
1,2,pli,2,0.292719,0.318883,0.436030,0.584100,0.195178,0.324630,0.352602,...,0.316805,0.455805,0.155347,0.312086,0.413950,0.599978,0.276919,0.315845,0.396189,0.538973
2,2,pli,3,0.293858,0.131834,0.375932,0.541556,0.285500,0.177590,0.339944,...,0.302541,0.449683,0.134922,0.074674,0.396658,0.638456,0.146139,0.134180,0.349079,0.531690
3,2,pli,4,0.106993,0.258264,0.382098,0.547303,0.141711,0.241283,0.321960,...,0.304271,0.444991,0.187288,0.228939,0.409769,0.639886,0.162533,0.299899,0.373405,0.537201
4,2,pli,5,0.267344,0.275909,0.354277,0.555398,0.225627,0.220839,0.280916,...,0.275206,0.423812,0.128241,0.233628,0.378185,0.591655,0.195630,0.255810,0.360064,0.551501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2375,42,wpli,115,0.377046,0.126250,0.195297,0.090652,0.457968,0.142317,0.196913,...,0.162483,0.155280,0.584357,0.190105,0.151936,0.153995,0.640407,0.273644,0.171674,0.165601
2376,42,wpli,116,0.613664,0.244323,0.126219,0.358264,0.433282,0.234579,0.126782,...,0.161964,0.353101,0.477210,0.100955,0.146389,0.347046,0.299419,0.112562,0.149547,0.346977
2377,42,wpli,117,0.508964,0.316342,0.110806,0.081628,0.473824,0.338044,0.080400,...,0.159102,0.213952,0.359050,0.205948,0.181841,0.230168,0.233635,0.191297,0.169004,0.251354
2378,42,wpli,118,0.251583,0.256624,0.219178,0.154116,0.306332,0.268266,0.182022,...,0.115851,0.148631,0.418033,0.108422,0.135640,0.159009,0.179893,0.099454,0.136583,0.191944
2379,42,wpli,119,0.586971,0.344756,0.234763,0.049423,0.560098,0.319582,0.232895,...,0.266422,0.075432,0.455566,0.248540,0.262647,0.077667,0.520368,0.290232,0.263531,0.074634

In [22]:
procdata_norm['shared']

,Session,Metric,Epoch,TP9_TP9_theta,TP9_TP9_alpha,TP9_TP9_beta,TP9_TP9_gamma,TP9_TP10_theta,TP9_TP10_alpha,TP9_TP10_beta,...,AF8_TP10_beta,AF8_TP10_gamma,AF8_AF7_theta,AF8_AF7_alpha,AF8_AF7_beta,AF8_AF7_gamma,AF8_AF8_theta,AF8_AF8_alpha,AF8_AF8_beta,AF8_AF8_gamma
0,2,pli,1,-1.256326,-0.573811,9.042647,6.028096,-0.801551,-1.415628,4.993547,...,4.329244,3.837719,1.151700,0.613205,6.632385,6.305241,-1.599655,-0.812497,9.049593,5.854561
1,2,pli,2,0.898303,3.134881,11.224476,6.969055,-0.550493,2.911653,8.724873,...,7.278161,4.812282,-1.157337,2.625178,7.309678,6.869381,0.991273,2.972259,10.843207,6.538085
2,2,pli,3,0.913041,-0.346501,9.142898,6.349627,0.574539,0.386925,8.270106,...,6.805282,4.726410,-1.438683,-1.648214,6.863960,7.415569,-1.121228,-0.200011,9.129872,6.429485
3,2,pli,4,-1.504244,2.006645,9.356461,6.433299,-1.216466,1.480546,7.624001,...,6.862639,4.660601,-0.717339,1.128533,7.201923,7.435858,-0.856413,2.693801,10.014551,6.511660
4,2,pli,5,0.570061,2.335049,8.392845,6.551158,-0.171234,1.129512,6.149429,...,5.899055,4.363546,-1.530718,1.212948,6.387802,6.751245,-0.321789,1.923909,9.529360,6.724915
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2375,42,wpli,115,-0.846437,-1.688854,-0.122037,-0.576095,0.191730,-1.438416,-0.068947,...,-0.244661,0.074529,1.243770,-0.822965,-0.410911,0.129051,1.435371,0.145995,-0.017933,0.162887
2376,42,wpli,116,0.912090,-0.404104,-1.162727,2.245886,-0.009139,-0.451637,-1.068754,...,-0.255877,2.706636,0.362310,-1.762245,-0.525571,2.709713,-0.962662,-1.608264,-0.499516,2.502543
2377,42,wpli,117,0.133972,0.379537,-1.394933,-0.671255,0.320749,0.654968,-1.729995,...,-0.317626,0.855194,-0.609759,-0.656050,0.207279,1.147306,-1.425300,-0.750796,-0.076043,1.269056
2378,42,wpli,118,-1.778871,-0.270253,0.237744,0.093135,-1.042136,-0.091339,-0.281246,...,-1.250780,-0.013934,-0.124524,-1.683569,-0.747762,0.196075,-1.803245,-1.751014,-0.781661,0.502700
2379,42,wpli,119,0.713713,0.688708,0.472550,-1.010856,1.022758,0.457514,0.444014,...,1.997874,-0.987886,0.184250,-0.207312,1.877681,-0.891287,0.591186,0.326650,1.981283,-1.010550

In [23]:
feat_mat = proc.build_feature_matrix(procdata_norm)

In [24]:
feat_mat

,Session,Target,TP9_TP9_theta,TP9_TP9_alpha,TP9_TP9_beta,TP9_TP9_gamma,TP9_TP10_theta,TP9_TP10_alpha,TP9_TP10_beta,TP9_TP10_gamma,...,AF8_TP10_beta,AF8_TP10_gamma,AF8_AF7_theta,AF8_AF7_alpha,AF8_AF7_beta,AF8_AF7_gamma,AF8_AF8_theta,AF8_AF8_alpha,AF8_AF8_beta,AF8_AF8_gamma
0,2,0,-1.256326,-0.573811,9.042647,6.028096,-0.801551,-1.415628,4.993547,4.422260,...,4.329244,3.837719,1.151700,0.613205,6.632385,6.305241,-1.599655,-0.812497,9.049593,5.854561
1,2,0,0.898303,3.134881,11.224476,6.969055,-0.550493,2.911653,8.724873,5.647135,...,7.278161,4.812282,-1.157337,2.625178,7.309678,6.869381,0.991273,2.972259,10.843207,6.538085
2,2,0,0.913041,-0.346501,9.142898,6.349627,0.574539,0.386925,8.270106,5.361547,...,6.805282,4.726410,-1.438683,-1.648214,6.863960,7.415569,-1.121228,-0.200011,9.129872,6.429485
3,2,0,-1.504244,2.006645,9.356461,6.433299,-1.216466,1.480546,7.624001,5.072314,...,6.862639,4.660601,-0.717339,1.128533,7.201923,7.435858,-0.856413,2.693801,10.014551,6.511660
4,2,0,0.570061,2.335049,8.392845,6.551158,-0.171234,1.129512,6.149429,4.853174,...,5.899055,4.363546,-1.530718,1.212948,6.387802,6.751245,-0.321789,1.923909,9.529360,6.724915
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2375,42,1,0.665508,1.575073,-1.026268,-1.074300,1.797739,1.559971,-0.616028,-0.118887,...,0.538683,0.574756,0.126373,-0.501814,0.719676,0.908968,-1.269193,-0.341462,0.974357,0.994272
2376,42,1,0.255034,-1.466093,-0.521467,1.310508,-0.193857,-1.106761,-0.633772,0.097608,...,-0.053201,-0.998159,-1.175831,-0.106088,-0.203481,-0.528230,1.028047,-0.358878,0.346302,-0.343883
2377,42,1,-0.541535,-0.466371,-1.563662,-0.224418,0.203886,-0.202356,-1.434918,-0.461564,...,1.675596,-0.843348,-0.468856,-0.716554,1.868301,-0.921288,-0.712519,-0.901937,1.727912,-0.521124
2378,42,1,-1.444669,-0.017747,0.493755,-0.648227,-0.949774,-0.441940,0.252149,-0.384170,...,1.526482,-1.005833,0.276634,0.818837,1.744708,-0.831475,1.574769,0.939938,1.329007,-1.012579
2379,42,1,0.173695,-1.609541,0.132458,-1.160128,-0.346592,-1.562161,-0.424969,-1.095898,...,1.797775,0.097455,-1.895384,-0.673002,2.250153,0.098344,-1.959501,0.097737,1.532207,-0.200569

In [25]:
stats_report = generate_report(feat_mat)

In [26]:
stats_report

,Session,Feature,Mean_Shared,Mean_Individual,Trend,p_value,Cliffs_delta,p_value_fdr,Significant
0,2,TP9_TP9_theta,-0.077147,-0.073379,increase,9.788441e-01,-0.004731,9.912345e-01,False
1,2,TP9_TP9_alpha,0.713504,1.461407,increase,5.351664e-06,-0.354707,3.848387e-05,True
2,2,TP9_TP9_beta,2.120188,6.162597,increase,2.290503e-10,-0.583786,3.054004e-09,True
3,2,TP9_TP9_gamma,2.823075,3.695877,increase,4.941517e-02,-0.191159,1.411862e-01,False
4,2,TP9_TP10_theta,-0.138171,-0.461529,decrease,2.415971e-03,0.211638,1.128629e-02,True
...,...,...,...,...,...,...,...,...,...
635,42,AF8_AF7_gamma,0.098520,-0.063569,decrease,2.165538e-01,0.109244,3.937341e-01,False
636,42,AF8_AF8_theta,0.074005,-0.106543,decrease,2.688109e-01,0.070122,4.587705e-01,False
637,42,AF8_AF8_alpha,0.155750,-0.028834,decrease,3.588668e-01,0.022385,5.601823e-01,False
638,42,AF8_AF8_beta,0.742280,0.301908,decrease,2.321060e-02,0.148930,7.818309e-02,False
639,42,AF8_AF8_gamma,0.043720,-0.090102,decrease,2.286197e-01,0.101476,4.075671e-01,False

In [29]:
import pickle
with open(r'C:\Users\josee\OneDrive\Documentos\GitHub\synchrony_pipeline\src\C1\outputs\feat_mat.pkl', "rb") as f:
    feat_mat = pickle.load(f)

In [30]:
feat_mat

,Session,Target,TP9_TP9_theta,TP9_TP9_alpha,TP9_TP9_beta,TP9_TP9_gamma,TP9_TP10_theta,TP9_TP10_alpha,TP9_TP10_beta,TP9_TP10_gamma,...,AF8_TP10_beta,AF8_TP10_gamma,AF8_AF7_theta,AF8_AF7_alpha,AF8_AF7_beta,AF8_AF7_gamma,AF8_AF8_theta,AF8_AF8_alpha,AF8_AF8_beta,AF8_AF8_gamma
0,2,0,-1.256326,-0.573811,9.042647,6.028096,-0.801551,-1.415628,4.993547,4.422260,...,4.329244,3.837719,1.151700,0.613205,6.632385,6.305241,-1.599655,-0.812497,9.049593,5.854561
1,2,0,0.898303,3.134881,11.224476,6.969055,-0.550493,2.911653,8.724873,5.647135,...,7.278161,4.812282,-1.157337,2.625178,7.309678,6.869381,0.991273,2.972259,10.843207,6.538085
2,2,0,0.913041,-0.346501,9.142898,6.349627,0.574539,0.386925,8.270106,5.361547,...,6.805282,4.726410,-1.438683,-1.648214,6.863960,7.415569,-1.121228,-0.200011,9.129872,6.429485
3,2,0,-1.504244,2.006645,9.356461,6.433299,-1.216466,1.480546,7.624001,5.072314,...,6.862639,4.660601,-0.717339,1.128533,7.201923,7.435858,-0.856413,2.693801,10.014551,6.511660
4,2,0,0.570061,2.335049,8.392845,6.551158,-0.171234,1.129512,6.149429,4.853174,...,5.899055,4.363546,-1.530718,1.212948,6.387802,6.751245,-0.321789,1.923909,9.529360,6.724915
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2375,42,1,0.665508,1.575073,-1.026268,-1.074300,1.797739,1.559971,-0.616028,-0.118887,...,0.538683,0.574756,0.126373,-0.501814,0.719676,0.908968,-1.269193,-0.341462,0.974357,0.994272
2376,42,1,0.255034,-1.466093,-0.521467,1.310508,-0.193857,-1.106761,-0.633772,0.097608,...,-0.053201,-0.998159,-1.175831,-0.106088,-0.203481,-0.528230,1.028047,-0.358878,0.346302,-0.343883
2377,42,1,-0.541535,-0.466371,-1.563662,-0.224418,0.203886,-0.202356,-1.434918,-0.461564,...,1.675596,-0.843348,-0.468856,-0.716554,1.868301,-0.921288,-0.712519,-0.901937,1.727912,-0.521124
2378,42,1,-1.444669,-0.017747,0.493755,-0.648227,-0.949774,-0.441940,0.252149,-0.384170,...,1.526482,-1.005833,0.276634,0.818837,1.744708,-0.831475,1.574769,0.939938,1.329007,-1.012579
2379,42,1,0.173695,-1.609541,0.132458,-1.160128,-0.346592,-1.562161,-0.424969,-1.095898,...,1.797775,0.097455,-1.895384,-0.673002,2.250153,0.098344,-1.959501,0.097737,1.532207,-0.200569

In [31]:
with open(r'C:\Users\josee\OneDrive\Documentos\GitHub\synchrony_pipeline\src\C1\outputs\eda_report.pkl', "rb") as f:
    eda_report = pickle.load(f)
eda_report

,Session,Feature,Mean_Shared,Mean_Individual,Trend,p_value,Cliffs_delta,p_value_fdr,Significant
0,2,TP9_TP9_theta,-0.077147,-0.073379,increase,9.788441e-01,-0.004731,9.912345e-01,False
1,2,TP9_TP9_alpha,0.713504,1.461407,increase,5.351664e-06,-0.354707,3.848387e-05,True
2,2,TP9_TP9_beta,2.120188,6.162597,increase,2.290503e-10,-0.583786,3.054004e-09,True
3,2,TP9_TP9_gamma,2.823075,3.695877,increase,4.941517e-02,-0.191159,1.411862e-01,False
4,2,TP9_TP10_theta,-0.138171,-0.461529,decrease,2.415971e-03,0.211638,1.128629e-02,True
...,...,...,...,...,...,...,...,...,...
635,42,AF8_AF7_gamma,0.098520,-0.063569,decrease,2.165538e-01,0.109244,3.937341e-01,False
636,42,AF8_AF8_theta,0.074005,-0.106543,decrease,2.688109e-01,0.070122,4.587705e-01,False
637,42,AF8_AF8_alpha,0.155750,-0.028834,decrease,3.588668e-01,0.022385,5.601823e-01,False
638,42,AF8_AF8_beta,0.742280,0.301908,decrease,2.321060e-02,0.148930,7.818309e-02,False
639,42,AF8_AF8_gamma,0.043720,-0.090102,decrease,2.286197e-01,0.101476,4.075671e-01,False